{% set name = "pyvistaqt" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82f1985c077be9bec41b6a3706172bbc94794f8d13ed24077417a6716e87e4a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - pyvista >=0.32.0
    - qtpy >=1.9.0
    - imageio >=2.5.0

test:
  imports:
    - pyvistaqt
  commands:
    - python -c "from packaging.version import parse; import pyvistaqt; assert parse(pyvistaqt.__version__) == parse('{{ version }}'), pyvistaqt.__version__"
  requires:
    - packaging
    - python {{ python_min }}

about:
  home: https://github.com/pyvista/pyvistaqt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A helper module for pyvista to enable you to plot using pyqt
  doc_url: http://qtdocs.pyvista.org

extra:
  recipe-maintainers:
    - hoechenberger
    - banesullivan
    - akaszynski
    - larsoner
    - GuillaumeFavelier
