{% set name = "pyvistaqt" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1cfdc41a920b629a80d948de4878ba90616511ad99ab70e622225763fce1050

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyvista >=0.25.0
    - pyqt >=5.11.3
    - qtpy >=1.9.0
    - imageio >=2.5.0

test:
  imports:
    - pyvistaqt

about:
  home: https://github.com/pyvista/pyvistaqt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A helper module for pyvista to enable you to plot using pyqt
  doc_url: http://qtdocs.pyvista.org

extra:
  recipe-maintainers:
    - hoechenberger
    - banesullivan
    - akaszynski
    - larsoner
    - GuillaumeFavelier
